name: msv
channels:
  - defaults
dependencies:
  - aiofiles=22.1.0=py311hecd8cb5_0
  - aiohttp=3.8.3=py311h6c40b1e_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aiosqlite=0.18.0=py311hecd8cb5_0
  - anyio=3.5.0=py311hecd8cb5_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.2=py311hecd8cb5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h6c40b1e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py311hecd8cb5_0
  - attrs=22.1.0=py311hecd8cb5_0
  - babel=2.11.0=py311hecd8cb5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py311hecd8cb5_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.5=py311hb9e55a9_0
  - brotli=1.0.9=hca72f7f_7
  - brotli-bin=1.0.9=hca72f7f_7
  - brotlipy=0.7.0=py311h6c40b1e_1002
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2023.05.30=hecd8cb5_0
  - certifi=2023.7.22=py311hecd8cb5_0
  - cffi=1.15.1=py311h6c40b1e_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py311hecd8cb5_0
  - colorama=0.4.6=py311hecd8cb5_0
  - comm=0.1.2=py311hecd8cb5_0
  - contourpy=1.0.5=py311ha357a0b_0
  - cryptography=41.0.2=py311h3b477ad_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py311hcec6c5f_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py311hecd8cb5_0
  - et_xmlfile=1.1.0=py311hecd8cb5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=hd8bbffd_0
  - frozenlist=1.3.3=py311h6c40b1e_0
  - gettext=0.21.0=he85b6c0_1
  - giflib=5.2.1=h6c40b1e_3
  - glib=2.69.1=hfff2838_2
  - gst-plugins-base=1.14.1=hcec6c5f_1
  - gstreamer=1.14.1=h6c40b1e_1
  - icu=58.2=h0a44026_3
  - idna=3.4=py311hecd8cb5_0
  - intel-openmp=2023.1.0=ha357a0b_43547
  - ipykernel=6.19.2=py311h4975b63_0
  - ipython=8.12.0=py311hecd8cb5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py311hecd8cb5_0
  - jedi=0.18.1=py311hecd8cb5_1
  - jinja2=3.1.2=py311hecd8cb5_0
  - joblib=1.2.0=py311hecd8cb5_0
  - jpeg=9e=h6c40b1e_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py311hecd8cb5_0
  - jupyter=1.0.0=py311hecd8cb5_8
  - jupyter_client=8.1.0=py311hecd8cb5_0
  - jupyter_console=6.6.3=py311hecd8cb5_0
  - jupyter_core=5.3.0=py311hecd8cb5_0
  - jupyter_events=0.6.3=py311hecd8cb5_0
  - jupyter_server=2.5.0=py311hecd8cb5_0
  - jupyter_server_fileid=0.9.0=py311hecd8cb5_0
  - jupyter_server_terminals=0.4.4=py311hecd8cb5_1
  - jupyter_server_ydoc=0.8.0=py311hecd8cb5_1
  - jupyter_ydoc=0.2.4=py311hecd8cb5_0
  - jupyterlab=3.6.3=py311hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py311hecd8cb5_0
  - jupyterlab_widgets=3.0.5=py311hecd8cb5_0
  - kiwisolver=1.4.4=py311hcec6c5f_0
  - krb5=1.20.1=h428f121_1
  - lcms2=2.12=hf1fd2bf_0
  - lerc=3.0=he9d5cce_0
  - libbrotlicommon=1.0.9=hca72f7f_7
  - libbrotlidec=1.0.9=hca72f7f_7
  - libbrotlienc=1.0.9=hca72f7f_7
  - libclang=12.0.0=default_hbc2896b_2
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.17=hb664fd8_0
  - libedit=3.1.20221030=h6c40b1e_0
  - libffi=3.4.4=hecd8cb5_0
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libiconv=1.16=hca72f7f_2
  - libllvm12=12.0.0=h9b2ccf5_3
  - libpng=1.6.39=h6c40b1e_0
  - libpq=12.15=h04015c4_1
  - libsodium=1.0.18=h1de35cc_0
  - libtiff=4.5.0=hcec6c5f_2
  - libwebp=1.2.4=hf6ce154_1
  - libwebp-base=1.2.4=h6c40b1e_1
  - libxml2=2.10.3=h930c0e2_0
  - libxslt=1.1.37=h6d1eb0e_0
  - llvm-openmp=14.0.6=h0dcd299_0
  - lxml=4.9.2=py311h6c40b1e_0
  - lz4-c=1.9.4=hcec6c5f_0
  - markupsafe=2.1.1=py311h6c40b1e_0
  - matplotlib-base=3.7.1=py311h11e8b89_1
  - matplotlib-inline=0.1.6=py311hecd8cb5_0
  - mistune=0.8.4=py311h6c40b1e_1000
  - mkl=2023.1.0=h59209a4_43558
  - mkl-service=2.4.0=py311h6c40b1e_1
  - mkl_fft=1.3.6=py311hdb55bb0_1
  - mkl_random=1.2.2=py311hdb55bb0_1
  - multidict=6.0.2=py311h6c40b1e_0
  - munkres=1.1.4=py_0
  - nbclassic=0.5.5=py311hecd8cb5_0
  - nbclient=0.5.13=py311hecd8cb5_0
  - nbconvert=6.5.4=py311hecd8cb5_0
  - nbformat=5.7.0=py311hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.5.6=py311hecd8cb5_0
  - notebook=6.5.4=py311hecd8cb5_0
  - notebook-shim=0.2.2=py311hecd8cb5_0
  - nspr=4.35=hcec6c5f_0
  - nss=3.89.1=hcec6c5f_0
  - numexpr=2.8.4=py311h728a8a3_1
  - numpy=1.25.0=py311h728a8a3_0
  - numpy-base=1.25.0=py311h53bf9ac_0
  - openai=0.27.4=py311hecd8cb5_0
  - openpyxl=3.0.10=py311h6c40b1e_0
  - openssl=3.0.9=hca72f7f_0
  - packaging=23.0=py311hecd8cb5_0
  - pandas=1.5.3=py311hc5848a5_0
  - pandas-stubs=1.5.3.230203=py311hecd8cb5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h23ab428_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py311hcec6c5f_0
  - pip=23.2.1=py311hecd8cb5_0
  - platformdirs=2.5.2=py311hecd8cb5_0
  - plotly=5.9.0=py311hecd8cb5_0
  - ply=3.11=py311hecd8cb5_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py311hecd8cb5_0
  - prompt-toolkit=3.0.36=py311hecd8cb5_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - psutil=5.9.0=py311h6c40b1e_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py311hecd8cb5_1
  - pyopenssl=23.2.0=py311hecd8cb5_0
  - pyparsing=3.0.9=py311hecd8cb5_0
  - pyqt=5.15.7=py311hcec6c5f_0
  - pyqt5-sip=12.11.0=py311hcec6c5f_0
  - pyrsistent=0.18.0=py311h6c40b1e_0
  - pysocks=1.7.1=py311hecd8cb5_0
  - python=3.11.4=hf27a42d_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-dotenv=0.21.0=py311hecd8cb5_0
  - python-fastjsonschema=2.16.2=py311hecd8cb5_0
  - python-json-logger=2.0.7=py311hecd8cb5_0
  - pytz=2022.7=py311hecd8cb5_0
  - pyyaml=6.0=py311h6c40b1e_1
  - pyzmq=25.1.0=py311hcec6c5f_0
  - qt-main=5.15.2=h719ae48_7
  - qt-webengine=5.15.9=h90a370e_4
  - qtconsole=5.4.2=py311hecd8cb5_0
  - qtpy=2.2.0=py311hecd8cb5_0
  - qtwebkit=5.212=hbfab81c_5
  - readline=8.2=hca72f7f_0
  - requests=2.29.0=py311hecd8cb5_0
  - rfc3339-validator=0.1.4=py311hecd8cb5_0
  - rfc3986-validator=0.1.1=py311hecd8cb5_0
  - scikit-learn=1.2.2=py311hcec6c5f_0
  - scipy=1.10.1=py311h224febf_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=68.0.0=py311hecd8cb5_0
  - sip=6.6.2=py311hcec6c5f_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py311hecd8cb5_1
  - soupsieve=2.4=py311hecd8cb5_0
  - sqlite=3.41.2=h6c40b1e_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=ha357a0b_0
  - tenacity=8.2.2=py311hecd8cb5_0
  - terminado=0.17.1=py311hecd8cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.2.1=py311hecd8cb5_0
  - tk=8.6.12=h5d9f67b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.2=py311h6c40b1e_0
  - tqdm=4.65.0=py311h85bffb1_0
  - traitlets=5.7.1=py311hecd8cb5_0
  - types-pytz=2022.4.0.0=py311hecd8cb5_1
  - typing-extensions=4.7.1=py311hecd8cb5_0
  - typing_extensions=4.7.1=py311hecd8cb5_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py311hecd8cb5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311hecd8cb5_1
  - websocket-client=0.58.0=py311hecd8cb5_4
  - wheel=0.38.4=py311hecd8cb5_0
  - widgetsnbextension=4.0.5=py311hecd8cb5_0
  - xz=5.4.2=h6c40b1e_0
  - y-py=0.5.9=py311h7242b5c_0
  - yaml=0.2.5=haf1e3a3_0
  - yarl=1.8.1=py311h6c40b1e_0
  - ypy-websocket=0.8.2=py311hecd8cb5_0
  - zeromq=4.3.4=h23ab428_0
  - zlib=1.2.13=h4dc903c_0
  - zstd=1.5.5=hc035e20_0
prefix: /usr/local/Caskroom/miniconda/base/envs/msv
